### ISSUE TITLE
Support binding params

### ISSUE THREAD

**Issue by skortobi** [orange-cloudfoundry/osb-cmdb-spike#25] opened 2020-02-25 09:59 UTC
### Expected behavior

As a cmdb-operator, in order to use brokers with specific binding params, I expect osb-cmdb to propagate params to backend broker

### Observed behavior
By default, no binding parameters is forwarded to the backend broker

related : https://github.com/orange-cloudfoundry/osb-cmdb-spike/issues/12

**Comment by gberche-orange** [comment] 2020-03-09 13:50
duplicate of #26, sorry @skortobi to have missed it

**Closed by gberche-orange** 2020-03-09 13:50 UTC
